server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://ietmdb:ietlab25@192.168.1.7:27017?authSource=admin
      database: IeTRootDB
  datasource:
    url: jdbc:postgresql://192.168.1.7:5432/iot_db
    username: ietpsql
    password: ietlab25
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mqtt:
  broker:
    url: tcp://192.168.1.7:1883
    username: testuser
    password: iet25
    client-id: iotroot-backend
    topic: test/topic

logging:
  level:
    root: WARN
    com.astraval.iotroot: INFO
  