server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:astraval25@iot.e4vu4bo.mongodb.net/user_platform
      database: iotRoot

logging:
  level:
    root: WARN
    com.astraval.iotroot: INFO
  